# Generated by Django 3.2 on 2021-04-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0006_auto_20210421_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistitem',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
