# Generated by Django 3.2 on 2021-04-30 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0015_alter_playlist_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlistitem',
            old_name='Playlist',
            new_name='playlist',
        ),
    ]
