# Generated by Django 3.2 on 2021-05-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_alter_video_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
